# Generated by Django 3.0.6 on 2020-06-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='option')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='slider')),
                ('offerDetail1', models.CharField(max_length=100)),
                ('offerDetail2', models.CharField(max_length=100)),
            ],
        ),
    ]
