# Generated by Django 3.0.6 on 2020-06-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_smalloption'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='topproducts')),
                ('image2', models.ImageField(upload_to='topproducts')),
                ('new', models.BooleanField(default=False)),
            ],
        ),
    ]
