# Generated by Django 3.0.6 on 2020-06-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20200607_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='topproducts')),
                ('image2', models.ImageField(upload_to='topproducts')),
                ('TopProduct', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('offerprice', models.IntegerField()),
                ('new', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='TopProduct',
        ),
    ]
