# Generated by Django 3.0.6 on 2020-06-18 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20200618_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='OnSale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
