# Generated by Django 3.0.6 on 2020-06-19 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20200618_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
    ]
